Repository watermelontools/watermelon-intellij, pull requests merged in 2023-10, with the labels that each got.

#59 Chore/update readme
  README.md
Labels: 🍉 Safe to Merge

#37 Change menu item name to avoid confusion
  src/main/resources/META-INF/plugin.xml
Labels: 🚨 Don't Merge

#60 Simplify code
  src/main/kotlin/com/watermelon/context/services/MyProjectService.kt
  src/main/kotlin/com/watermelon/context/toolWindow/MyToolWindowFactory.kt
Labels: 👀 Take a deeper dive
